### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by abecx** [siebenmann/smtpd#3]
I was attempting to compile the latest version and I received the message:

abecx@[pi.abe.cx]:~/dev/smtpd $ make
cd cmd && go build -o ../sinksmtp
# _/home/abecx/dev/smtpd/cmd
./rlex.go:337: syntax error: unexpected range, expecting {
Makefile:2: recipe for target 'sinksmtp' failed
make: *** [sinksmtp] Error 2

The "for range l.items" on 337 does not appear to do anything so I commented it out and was able to compile.

**Comment by siebenmann** [comment]
Which version of go do you have? Check with `go version`. I may have code there that requires a more recent version of the language than you're using.

(In general, the cmd/ subdirectory is out of date and can be ignored. The stuff there got so big that I moved it to its own repo, [sinksmtp](https://github.com/siebenmann/sinksmtp), but I never cleaned up the smtpd package to reflect this. My bad and I'll take care of it soon, so at least cmd/ doesn't get built by the Makefile.)

**Comment by abecx** [comment]
I am using: 
go version go1.3.3 linux/arm
this time around.

**Comment by siebenmann** [comment]
While I don't know the exact Go version requirements of my code here, I strongly suggest updating to a more recent version of the Go toolchain; it's clearly not fully compatible with 1.3. The `range` statement here is intended to drain the `l.items` channel of anything further sent on it (exiting the loop when the channel is closed), which insures that the lexer goroutine always exits even if there is eg a syntax error that causes the parser to stop.

(This isn't necessarily an issue if you're not going to use [sinksmtp](https://github.com/siebenmann/sinksmtp), just the `smtpd` package (assuming that smtpd itself builds and works with 1.3), but if you do want to use sinksmtp it's going to be a problem even if you use the current version from its new repo. And you may well run across other Go code that assumes a more recent version of the language than 1.3.)

**Comment by abecx** [comment]
In this particular use case, I am using sinksmtp as a catch all for appliances that don't have an API but can email.  I will download and compile a newer version of go as that makes more sense.  Thanks for your insight.
